In [657]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [658]:
data = pd.read_csv("pima-indians-diabetes.csv")
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [659]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=20)

In [660]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Visualization

In [662]:
from scipy.stats import pearsonr
correlations = []
p_values = []
# Calculate Pearson correlation and p-value for each feature
for feature in x.T:
    corr, p_value = pearsonr(feature, y)
    correlations.append(corr)
    p_values.append(p_value)
np.set_printoptions(suppress=True)

In [663]:
correlations

[0.22108652807563128,
 0.4658559385380011,
 0.06488177904767567,
 0.07326497576626488,
 0.13198375600374435,
 0.2926954797181888,
 0.17324535270149824,
 0.23641745829787397]

In [664]:
p_values

[6.027649758892254e-10,
 1.4091419155128138e-42,
 0.07251877618697655,
 0.042511930345724355,
 0.0002470068592988624,
 1.2866893849050026e-16,
 1.3880883400589505e-06,
 3.3325545895850345e-11]

In [665]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
model1 = LogisticRegression()
model1

LogisticRegression()

In [666]:
model1.fit(x_train,y_train)
y_pred = model1.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[113  13]
 [ 34  32]]


In [667]:
accuracy_score(y_test,y_pred)

0.7552083333333334

In [668]:
accuracies = cross_val_score(estimator = model1, X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 77.53 %
Standard Deviation: 6.74 %


In [669]:
import joblib 
joblib.dump(model1,"sugar_pred.pkl")

['sugar_pred.pkl']

In [710]:
model1.predict(sc.transform([[137.0, 70.0, 0.0, 38.0, 0.0, 33.2, 0.17, 22.0]]))

array([1], dtype=int64)

In [712]:
sc.inverse_transform([x_test[0]])

array([[  0.  , 137.  ,  70.  ,  38.  ,   0.  ,  33.2 ,   0.17,  22.  ]])

In [698]:
import joblib 
joblib.dump(sc,"sc.pkl")

['sc.pkl']